### ISSUE TITLE
New trigger entity logics

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/docs#141]
https://github.com/momentum-mod/game/pull/1126

**Comment by xen-000** [comment]
Since it can't be documented in the FGD might as well explain it here.

The collectible system essentially boils down to a couple inputs and a filter:

- `AddCollectible` input: Add the firing entity to the target player's list of collectibles. The input can optionally be passed parameters in the format `<required>:<weight>`, where `required` is the targetname of a collectible that must already be collected and `weight` is the weight of the collectible that gets added to the counter. If desired, only one of the parameters can be passed. By default, there is no required collectible and the weight is 1.
- `ClearCollectibles` input: Clears the target player's collectible list and resets the counter.
- `filter_momentum_collectibles` entity: A filter that simply checks the player's collectible counter against a specified value and passes if it's higher.

Collectibles are saved in savelocs and when the player enters practice mode during a run.
